version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/interface"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "npm"
    groups:
      patch-updates:
        update-types:
          - "patch"
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "cargo"
    groups:
      patch-updates:
        update-types:
          - "patch"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
